# Generated by Django 4.2.7 on 2025-12-31 22:48

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(default='سکه', help_text='e.g. Coins, Credits', max_length=50)),
                ('currency_symbol', models.CharField(default='🪙', max_length=10)),
                ('tokens_per_credit', models.PositiveIntegerField(default=2000, help_text='How many LLM tokens equal 1 Credit?')),
                ('daily_free_credits', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Credits reset daily for every user.', max_digits=10)),
                ('transcription_cost_per_minute', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Cost in Credits per minute of audio.', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Economy Configuration',
                'verbose_name_plural': 'Economy Configuration',
            },
        ),
        migrations.CreateModel(
            name='BillingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('percent', models.PositiveIntegerField(help_text='Discount percentage (1-100)')),
                ('max_amount_per_usage', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for discount amount per single order', max_digits=12, null=True)),
                ('max_fund', models.DecimalField(blank=True, decimal_places=2, help_text='Code stops working if used_fund >= max_fund.', max_digits=15, null=True)),
                ('used_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transaction_ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('authority', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('SPEND', 'Spend (Tokens)'), ('RESET', 'Daily Reset'), ('ADJUSTMENT', 'Admin Adjustment'), ('SERVICE', 'Service Charge')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_plan', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19)),
                ('balance_paid', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19)),
                ('daily_free_used', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
