# Generated by Django 4.2.7 on 2026-01-01 15:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Internal ID (e.g. 'pro-plan')", unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, help_text='Price in Toman', max_digits=12)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Length of the subscription')),
                ('included_credits', models.DecimalField(decimal_places=10, default=Decimal('0.0'), help_text="Credits credited to 'Plan Balance' upon purchase.", max_digits=19)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userwallet',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingproduct',
            name='credit_amount',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('SPEND', 'Spend (Tokens)'), ('RESET', 'Daily Reset'), ('ADJUSTMENT', 'Admin Adjustment'), ('SERVICE', 'Service Charge'), ('PLAN', 'Plan Activation')], max_length=20),
        ),
        migrations.AddField(
            model_name='billingproduct',
            name='linked_plan',
            field=models.ForeignKey(blank=True, help_text='If set, purchasing this product activates the subscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='billing.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='active_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='billing.subscriptionplan'),
        ),
    ]
