# Generated by Django 4.2.7 on 2026-01-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscriptionplan_userwallet_plan_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='bank_card_number',
            field=models.CharField(blank=True, default='6037997500000000', max_length=20),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='bank_holder_name',
            field=models.CharField(blank=True, default='نام صاحب حساب', max_length=100),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='manual_payment_tips',
            field=models.TextField(blank=True, default='لطفا پس از واریز، شناسه پرداخت را وارد کنید.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('WAITING', 'Waiting for Approval'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
