# Generated by Django 4.2.7 on 2026-01-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billingconfig_bank_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='max_amount_per_usage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cap for discount amount per single order', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='max_fund',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Code stops working if used_fund >= max_fund.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Price in Toman', max_digits=18),
        ),
    ]
