# Generated by Django 4.2.7 on 2026-01-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_billingproduct_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(default='عمومی', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='support_address',
            field=models.TextField(blank=True, default='تهران، خیابان ولیعصر'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='support_email',
            field=models.EmailField(blank=True, default='support@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='support_phone',
            field=models.CharField(blank=True, default='09123456789', max_length=50),
        ),
    ]
