# Generated by Django 4.2.7 on 2026-02-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_faq_billingconfig_support_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='audience',
            field=models.CharField(choices=[('ALL', 'All'), ('VISITOR', 'Visitor'), ('EXPERT', 'Expert')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='eligible_expert_professions',
            field=models.JSONField(blank=True, default=list, help_text='List of eligible expert profession slugs for EXPERT audience plans.'),
        ),
    ]
