# Generated by Django 4.2.7 on 2026-04-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_subscriptionplan_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='support_contacts',
            field=models.JSONField(blank=True, default=list, help_text='Structured support contacts for UI display (role/name/phone).'),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='support_postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
