# Generated by Django 4.2.7 on 2026-01-08 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_contextdefinition_userrole_customuser_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='Dynamic form data submitted by the user.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Reason for rejection or internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='users.userrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Verification Request',
                'verbose_name_plural': 'Role Verification Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('REGISTERED', 'Registered & Linked')], default='SENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Markdown supported')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='doctors/avatars/')),
                ('clinic_address', models.TextField(blank=True)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('is_public', models.BooleanField(default=False, help_text="Show in the 'Find a Doctor' directory?")),
                ('accepting_new_patients', models.BooleanField(default=True, help_text='If False, patients cannot send new appointment requests.')),
                ('meeting_price', models.DecimalField(decimal_places=2, default=0, help_text='Cost per session (optional)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_PATIENT', 'Waiting for Patient'), ('PENDING_DOCTOR', 'Waiting for Doctor'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='PENDING_PATIENT', max_length=20)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text="Snapshot of the patient's request details (Symptoms, History, etc).")),
                ('notes', models.TextField(blank=True, help_text="Private administrative notes for the doctor (e.g. 'Referral from Dr. X').")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(help_text='The professional managing the treatment.', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_connections', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='The user receiving care.', on_delete=django.db.models.deletion.CASCADE, related_name='patient_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', 'status'], name='vania_core__doctor__d2d9e6_idx'), models.Index(fields=['patient', 'status'], name='vania_core__patient_792811_idx')],
                'unique_together': {('doctor', 'patient')},
            },
        ),
        migrations.CreateModel(
            name='SecureMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient'], name='vania_core__sender__91ac9c_idx'), models.Index(fields=['recipient', 'is_read'], name='vania_core__recipie_aa770d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('CONNECTION_REQUEST', 'درخواست مشاوره'), ('TASK_ASSIGNED', 'تکلیف جدید'), ('FORM_REQUEST', 'درخواست تکمیل فرم'), ('NEW_MESSAGE', 'پیام جدید'), ('SYSTEM', 'پیام سیستم')], default='SYSTEM', max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='vania_core__recipie_917406_idx')],
            },
        ),
    ]
