# Generated by Django 4.2.7 on 2026-01-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vania_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securemessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='secure_messages/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='securemessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('FILE', 'File')], default='TEXT', max_length=10),
        ),
        migrations.AddField(
            model_name='securemessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores file size, duration, etc.'),
        ),
        migrations.AlterField(
            model_name='securemessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
