# Generated by Django 4.2.7 on 2026-01-28 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vania_core', '0002_securemessage_attachment_securemessage_message_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Tehran - North, Isfahan, etc.', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='vania_core.location'),
        ),
    ]
