# Generated by Django 4.2.7 on 2026-03-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vania_core', '0004_googlecalendarconnection_expertmeetinglink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expertmeetinglink',
            new_name='vania_core__creator_28a3d4_idx',
            old_name='vania_core__creator_8fafef_idx',
        ),
        migrations.RenameIndex(
            model_name='expertmeetinglink',
            new_name='vania_core__visitor_e85874_idx',
            old_name='vania_core__visitor_27217e_idx',
        ),
    ]
