# Generated by Django 4.2.7 on 2026-03-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vania_core', '0006_caseaccessgrant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='caseaccessgrant',
            new_name='vania_core__patient_cfc628_idx',
            old_name='vania_core__patient_55fcf0_idx',
        ),
        migrations.RenameIndex(
            model_name='caseaccessgrant',
            new_name='vania_core__grantee_8b656e_idx',
            old_name='vania_core__grantee_e8f9e3_idx',
        ),
        migrations.RenameIndex(
            model_name='caseaccessgrant',
            new_name='vania_core__owner_d_0da942_idx',
            old_name='vania_core__owner_d8d026_idx',
        ),
    ]
