# Generated by Django 4.2.7 on 2026-03-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_expertprofession_customuser_expert_verification_meta_and_more'),
        ('vania_core', '0007_rename_vania_core__patient_55fcf0_idx_vania_core__patient_cfc628_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseContextEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Case Record',
                'verbose_name_plural': 'Case Records',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.usercontextentry',),
        ),
    ]
