# Generated by Django 4.2.7 on 2026-05-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vania_core', '0008_casecontextentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('page_path', models.CharField(help_text='Page path or full URL. Examples: /dashboard/patients or https://panel.vaniaapp.app/chat/tashkil-parvande/', max_length=500)),
                ('normalized_path', models.CharField(db_index=True, editable=False, max_length=500)),
                ('video', models.FileField(upload_to='tutorials/videos/')),
                ('is_public', models.BooleanField(default=True, help_text='If enabled, users can see this tutorial.')),
                ('match_prefix', models.BooleanField(default=False, help_text='Enable for dynamic nested pages. Example: /chat/tashkil-parvande matches /chat/tashkil-parvande/local-...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['normalized_path', 'title'],
                'indexes': [models.Index(fields=['is_public', 'normalized_path'], name='vania_core__is_publ_542fcd_idx')],
            },
        ),
    ]
