# Generated by Django 4.2.7 on 2026-05-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vania_core', '0009_pagetutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetutorial',
            name='video',
            field=models.FileField(max_length=500, upload_to='tutorials/videos/'),
        ),
    ]
