# Generated by Django 4.2.7 on 2025-12-31 22:48

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCanvasConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default_open', models.BooleanField(default=False, help_text='Should this canvas open automatically when a chat starts?')),
                ('permission_level', models.CharField(choices=[('READ', 'Read Only'), ('WRITE', 'Read & Write')], default='WRITE', max_length=10)),
            ],
            options={
                'verbose_name': 'Agent Canvas Configuration',
            },
        ),
        migrations.CreateModel(
            name='AgentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL identifier', unique=True)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField(help_text='Core personality.')),
                ('model_id', models.CharField(default='gpt-4o', help_text='The ID of the LLM to use.', max_length=100)),
                ('is_free', models.BooleanField(default=True, help_text='If True, all users can access this agent without purchase.')),
                ('access_price', models.DecimalField(decimal_places=0, default=0, help_text='Price to buy access (in Toman/Currency).', max_digits=12)),
                ('license_duration_days', models.PositiveIntegerField(default=365, help_text='How many days the license lasts after purchase.')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of short tags for UI filtering.')),
                ('user_guide', models.TextField(blank=True, help_text='Markdown text visible in the Agent Card.')),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='List of technical domains to load.')),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('static_tools', models.JSONField(blank=True, default=list)),
                ('enable_reasoning', models.BooleanField(default=False)),
                ('reasoning_effort', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('none', 'None'), ('default', 'Default')], default='medium', max_length=20)),
                ('enable_mem0', models.BooleanField(default=False)),
                ('cost_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Function name used by the LLM.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Docstring extracted from the function.')),
                ('import_path', models.CharField(help_text='Python dot-path', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('current_state', models.JSONField(default=dict)),
                ('is_visible', models.BooleanField(default=True, help_text='Was this tab open/visible last time?')),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanvasType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="Unique identifier, e.g., 'sales-dashboard-v1'", unique=True)),
                ('description', models.TextField(blank=True, help_text='Context description for the LLM.')),
                ('component_key', models.CharField(help_text="Key for the React Component (e.g., 'RECHARTS_DASHBOARD', 'TEXT_EDITOR')", max_length=100)),
                ('schema_definition', models.JSONField(blank=True, default=dict)),
                ('default_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable title (e.g., 'Skin Type Quiz').", max_length=255)),
                ('handle', models.SlugField(help_text="Unique key used by the Agent tool to trigger this form (e.g., 'skin_quiz').", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Instructions for the Agent: When should this form be used?')),
                ('fields', django_jsonform.models.fields.JSONField(blank=True, default=list, help_text='Define the form fields using the visual builder.')),
                ('handler', models.CharField(blank=True, help_text='The Python logic class that processes this form (from capabilities/).', max_length=255, null=True)),
                ('schema_definition', models.JSONField(blank=True, default=list, help_text='[Legacy] Raw JSON schema definition.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interaction Form',
                'verbose_name_plural': 'Interaction Forms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='knowledge_docs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('prompt', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserAgentLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set false to manually revoke access.')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='services.agentservice')),
            ],
        ),
    ]
