# Generated by Django 4.2.7 on 2025-12-31 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useragentlicense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicesuggestion',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='services.agentservice'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='services.knowledgebase'),
        ),
        migrations.AddField(
            model_name='interactionform',
            name='context_mapping',
            field=models.ForeignKey(blank=True, help_text='[Legacy] If set, data is saved directly to User Context.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='users.contextdefinition'),
        ),
        migrations.AddField(
            model_name='canvasinstance',
            name='canvas_def',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.canvastype'),
        ),
        migrations.AddField(
            model_name='agentservice',
            name='custom_tools',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.availabletool'),
        ),
        migrations.AddField(
            model_name='agentservice',
            name='interaction_forms',
            field=models.ManyToManyField(blank=True, related_name='agents', to='services.interactionform'),
        ),
        migrations.AddField(
            model_name='agentservice',
            name='knowledge_bases',
            field=models.ManyToManyField(blank=True, related_name='agents', to='services.knowledgebase'),
        ),
        migrations.AddField(
            model_name='agentcanvasconfig',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_configs', to='services.agentservice'),
        ),
        migrations.AddField(
            model_name='agentcanvasconfig',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='services.canvastype'),
        ),
        migrations.AddIndex(
            model_name='useragentlicense',
            index=models.Index(fields=['user', 'agent', 'expires_at'], name='services_us_user_id_2116dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useragentlicense',
            unique_together={('user', 'agent')},
        ),
        migrations.AddIndex(
            model_name='canvasinstance',
            index=models.Index(fields=['session_id', 'created_at'], name='services_ca_session_75a6c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentcanvasconfig',
            unique_together={('agent', 'canvas')},
        ),
    ]
