# Generated by Django 4.2.7 on 2026-01-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscriptionplan_userwallet_plan_expires_at_and_more'),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentservice',
            name='access_price',
        ),
        migrations.RemoveField(
            model_name='agentservice',
            name='license_duration_days',
        ),
        migrations.AddField(
            model_name='agentservice',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='Which subscription plans grant access to this agent?', related_name='agents', to='billing.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='agentservice',
            name='is_free',
            field=models.BooleanField(default=True, help_text='If True, all users can access this agent regardless of their plan.'),
        ),
        migrations.DeleteModel(
            name='UserAgentLicense',
        ),
    ]
