# Generated by Django 4.2.7 on 2026-01-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_agentservice_access_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentservice',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
