# Generated by Django 4.2.7 on 2026-01-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_agentservice_extra_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentservice',
            name='demo_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object defining rules for users without a plan (e.g., limits, UI locks).'),
        ),
    ]
