# Generated by Django 4.2.7 on 2026-01-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_agentservice_enable_mem0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentservice',
            name='interaction_forms',
        ),
        migrations.AlterField(
            model_name='agentservice',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, help_text="List of technical domains to load (e.g., 'trade', 'shop')."),
        ),
        migrations.AlterField(
            model_name='agentservice',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict, help_text='UI settings like canvas width.'),
        ),
        migrations.AlterField(
            model_name='agentservice',
            name='is_free',
            field=models.BooleanField(default=False, help_text='If True, all users can access this agent regardless of their plan.'),
        ),
        migrations.AlterField(
            model_name='agentservice',
            name='model_id',
            field=models.CharField(default='gpt-4o', help_text='The ID of the LLM to use (e.g., gpt-4o, gpt-5.1).', max_length=100),
        ),
        migrations.AlterField(
            model_name='agentservice',
            name='static_tools',
            field=models.JSONField(blank=True, default=list, help_text='List of built-in tools. Managed via checkboxes in Admin.'),
        ),
        migrations.AlterField(
            model_name='agentservice',
            name='system_prompt',
            field=models.TextField(help_text='Core personality and instructions for the AI.'),
        ),
        migrations.AlterField(
            model_name='agentservice',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of short tags for UI filtering. Managed via text input in Admin.'),
        ),
        migrations.DeleteModel(
            name='InteractionForm',
        ),
    ]
