# Generated by Django 4.2.7 on 2026-02-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_agentservice_interaction_forms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentservice',
            name='audience',
            field=models.CharField(choices=[('ALL', 'All'), ('VISITOR', 'Visitor'), ('EXPERT', 'Expert')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='agentservice',
            name='eligible_expert_professions',
            field=models.JSONField(blank=True, default=list, help_text='List of eligible expert profession slugs for EXPERT audience agents.'),
        ),
        migrations.AddField(
            model_name='agentservice',
            name='requires_visitor_selector',
            field=models.BooleanField(default=False, help_text='If True, frontend should require visitor/case selector before use.'),
        ),
    ]
