# backend/vania_core/schemas.py
from typing import List, Optional, Dict, Any
from enum import Enum
from pydantic import BaseModel, Field
from datetime import datetime

# ==============================================================================
# == ENUMERATIONS: Standardized choices for Vania system states and types
# ==============================================================================

class TherapyPhase(str, Enum):
    """Defines the stages of the 6-Phase Clinical Protocol."""
    PHASE_1_ANALYSIS = "PHASE_1_ANALYSIS"       # Analyze Tests & Demographics
    PHASE_2_APPROACHES = "PHASE_2_APPROACHES"   # Agent proposes 17 approaches
    PHASE_3_SELECTION = "PHASE_3_SELECTION"     # Doctor selects approach
    PHASE_4_PROTOCOL = "PHASE_4_PROTOCOL"       # Agent writes protocols for future sessions
    PHASE_5_EXECUTION = "PHASE_5_EXECUTION"     # Active Sessions Loop (Running therapy)
    PHASE_6_APPENDIX = "PHASE_6_APPENDIX"       # Ongoing Culture Prescription

class SessionStatus(str, Enum):
    """Defines the state of an individual therapy session within the Roadmap."""
    DRAFT = "DRAFT"         # A future session that has been planned but has no protocol yet.
    READY = "READY"         # A future session where the AI has generated the doctor's instructions.
    COMPLETED = "COMPLETED" # A past session that has been executed and has a report.

class RescueDimension(str, Enum):
    """The 9 dimensions of the 'Rescue Net' (Tour-e Nejat) framework."""
    PERSONAL = "PERSONAL"               # رشد شخصی
    RELATIONSHIP = "RELATIONSHIP"       # رشد ارتباط سودمند (e.g., family, partner)
    CAREER = "CAREER"                   # رشد شغلی-تحصیلی
    EMOTIONAL = "EMOTIONAL"             # رشد عاطفی
    INTELLECTUAL = "INTELLECTUAL"       # رشد فکری
    FRIENDSHIP = "FRIENDSHIP"           # رشد ارتباط با دوستان
    ENVIRONMENT = "ENVIRONMENT"         # رشد محیطی (physical space, nature)
    SOLITUDE = "SOLITUDE"               # رشد تنهایی (managing being alone)
    RECREATION = "RECREATION"           # رشد تفریحی-ورزشی

class ResourceType(str, Enum):
    """The types of cultural resources that can be prescribed in the Thought Appendix."""
    BOOK = "BOOK"
    POEM = "POEM"
    MOVIE = "MOVIE"

# ==============================================================================
# == PILLAR 1: SESSION SUPPORT DOCUMENT (The Report Artifact)
# ==============================================================================

class SessionSupportDoc(BaseModel):
    """
    Pydantic model for the structured JSON of a finalized session report (سند پشتیبان).
    This is the output of Phase 5.
    """
    session_number: int
    date: str
    topic: str
    
    # Analysis from the session
    symptoms_analysis: str
    approaches_used: List[str]
    techniques_used: List[str]
    
    # Patient-facing content
    flashcards: List[Dict[str, str]] = Field(default_factory=list, description="List of {'title': '...', 'content': '...'} for patient reminders.")
    technique_examples: List[str] = Field(default_factory=list)
    
    # Strategic planning
    swot_analysis: Dict[str, List[str]] = Field(default_factory=dict, description="Dict with keys 'Strengths', 'Weaknesses', 'Opportunities', 'Threats'.")
    future_challenges: str
    smart_goals: List[str] = Field(default_factory=list)
    
    # Link to other pillars
    rescue_net_review: List[str] = Field(default_factory=list, description="Notes on which Rescue Net dimensions were addressed.")
    
    # Metadata
    private_admin_notes: str = ""
    is_finalized: bool = True

# ==============================================================================
# == PILLAR 2: THERAPY ROADMAP (The Central Plan)
# ==============================================================================

class RoadmapSession(BaseModel):
    """Represents a single session (past, present, or future) in the therapy plan."""
    session_number: int
    title: str
    status: SessionStatus = SessionStatus.DRAFT
    scheduled_date: Optional[str] = None
    
    # Private instructions for the doctor generated by the AI in Phase 4
    doctor_instructions: Optional[str] = None 
    
    # Link to the full SessionSupportDoc (UserContextEntry ID) once the session is completed
    doc_id: Optional[str] = None 

class TherapyRoadmap(BaseModel):
    """
    The singleton Pydantic model for the `therapy_roadmap` context key.
    This is the master plan for the entire treatment.
    """
    current_phase: TherapyPhase = TherapyPhase.PHASE_1_ANALYSIS
    treatment_approaches: List[str] = Field(default_factory=list, description="List of approaches selected by the doctor in Phase 3.")
    sessions: List[RoadmapSession] = Field(default_factory=list)
    
    # The active session number the doctor is currently working on
    active_session_number: Optional[int] = None 
    
    # Metadata
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.now().isoformat())

# ==============================================================================
# == PILLAR 3: RESCUE NET (Patient Tasks)
# ==============================================================================

class RescueTask(BaseModel):
    """Represents a single task/homework assigned to the patient, tagged with a dimension."""
    id: str
    text: str
    dimension: RescueDimension
    status: str = "PENDING" # "PENDING" | "DONE"
    created_at: str
    completed_at: Optional[str] = None

class RescueNetState(BaseModel):
    """The root model for the `patient_tasks` context key."""
    tasks: List[RescueTask] = Field(default_factory=list)

# ==============================================================================
# == PILLAR 4: THOUGHT APPENDIX (Cultural Prescriptions)
# ==============================================================================

class CulturalResource(BaseModel):
    """Represents a single prescribed book, poem, or movie."""
    id: str
    type: ResourceType
    title: str
    creator: str # Author, Poet, or Director
    reason_for_prescription: str
    content_excerpt: Optional[str] = None # The poem text or a key quote
    status: str = "SUGGESTED" # "SUGGESTED" | "CONSUMED"
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat())

class ThoughtAppendix(BaseModel):
    """The root model for the `thought_appendix_library` context key."""
    resources: List[CulturalResource] = Field(default_factory=list)

# ==============================================================================
# == PILLAR 5: MEDICATION PLAN
# ==============================================================================

class MedicationEntry(BaseModel):
    """Represents a single prescribed medication entry inside a case."""
    id: str
    drug_name: str
    dosage: str = ""
    usage_instructions: str = ""
    timing: str = ""
    duration: str = ""
    notes: str = ""
    prescribed_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    doctor_id: Optional[int] = None
    doctor_name: Optional[str] = None
    case_id: Optional[str] = None


class MedicationPlan(BaseModel):
    """The root model for the case-scoped medication plan."""
    medications: List[MedicationEntry] = Field(default_factory=list)
