from typing import List, Dict

# Stable catalog IDs for psychology tests that can be prescribed to patients.
TEST_CATALOG: List[Dict[str, str]] = [
    {"id": 1, "title": "تست آسیب‌های روانی مرتبط با جنگ (WPT)", "url": "https://esanj.ir/war-related-psychological-trauma-test"},
    {"id": 2, "title": "تست اختلال دوقطبی (BDSQ)", "url": "https://esanj.ir/bipolar-disorder-test"},
    {"id": 3, "title": "تست ذهن آگاهی پنج عاملی (FFMQ)", "url": "https://esanj.ir/mindfulness-five-facet-test"},
    {"id": 4, "title": "تست استعدادیابی کلیفتون (CSTA)", "url": "https://esanj.ir/clifton-strengths-test"},
    {"id": 5, "title": "تست تشخیص اوتیسم (GARS-3)", "url": "https://esanj.ir/gilliam-autism-test"},
    {"id": 6, "title": "تست عزت نفس کوپر اسمیت (CSEI-AD)", "url": "https://esanj.ir/coopersmith-self-esteem-test-adult-form"},
    {"id": 7, "title": "تست رغبت سنج شغلی و تحصیلی هالند (HII)", "url": "https://esanj.ir/hollands-interest-test"},
    {"id": 8, "title": "تست نیازهای اساسی گلاسر (BNQ)", "url": "https://esanj.ir/glasser-basic-needs-test"},
    {"id": 9, "title": "تست کمال گرایی هیل (HPI)", "url": "https://esanj.ir/hill-perfectionism-test"},
    {"id": 10, "title": "تست میلون 4 (MCMI-IV)", "url": "https://esanj.ir/millon-mcmi-iv-test"},
    {"id": 11, "title": "تست قصه عشق (LSS)", "url": "https://esanj.ir/love-story-test-lss"},
    {"id": 12, "title": "تست شخصیت شناسی MBTI کودکان (MMTIC)", "url": "https://esanj.ir/mmtic-mbti-child-test"},
    {"id": 13, "title": "تست شخصیت شناسی MMPI فرم 370 سوالی", "url": "https://esanj.ir/mmpi-test-370"},
    {"id": 14, "title": "تست شخصیت شناسی نئو (NEO FFI) فرم کوتاه - نسخه پیشرفته", "url": "https://esanj.ir/neo-ffi-personality-test"},
    {"id": 15, "title": "تست شخصیت شناسی MMPI فرم بلند (567 سوالی)", "url": "https://esanj.ir/mmpi-test-567"},
    {"id": 16, "title": "تست شخصیت شناسی نئو (NEO PI-R) - نسخه پیشرفته", "url": "https://esanj.ir/neo-pi-r-personality-test"},
    {"id": 17, "title": "تست دیسک DISC", "url": "https://esanj.ir/disc-test"},
    {"id": 18, "title": "تست استروپ معنایی - سرعت توجه (SST)", "url": "https://esanj.ir/semantic-stroop-test"},
    {"id": 19, "title": "تست افکار خودکشی بک (BSSI)", "url": "https://esanj.ir/suicide-ideation-scale"},
    {"id": 20, "title": "تست دسته بندی کارت های ویسکانسین (WCST)", "url": "https://esanj.ir/wisconsin-card-sorting-test"},
    {"id": 21, "title": "تست طرحواره های ناسازگار یانگ (YEMSQ)", "url": "https://esanj.ir/young-early-maladaptive-schema-test"},
    {"id": 22, "title": "تست بهزیستی روانی ریف (PWB)", "url": "https://esanj.ir/psychological-well-being-test"},
    {"id": 23, "title": "تست امید میلر (MHS)", "url": "https://esanj.ir/miler-hope-test"},
    {"id": 24, "title": "تست هوش هیجانی EQ کودکان (CEIT-R) - تصویری", "url": "https://esanj.ir/childs-emotional-intelligence-eq-test"},
    {"id": 25, "title": "تست اضطراب کودکان اسپنس (SCAS)", "url": "https://esanj.ir/children-anxiety-scale"},
    {"id": 26, "title": "تست احساس تنهایی (SLFS)", "url": "https://esanj.ir/loneliness-feeling-scale"},
    {"id": 27, "title": "تست اضطراب اجتماعی (SAIN)", "url": "https://esanj.ir/social-anxiety-inventory"},
    {"id": 28, "title": "تست سبک های فرزندپروری بامریند (PSI)", "url": "https://esanj.ir/baumrind-parenting-styles"},
    {"id": 29, "title": "تست اختلالات روانی SCL-90", "url": "https://esanj.ir/symptom-checklist-90"},
    {"id": 30, "title": "تست شخصیت 16 عاملی کتل (16PF)", "url": "https://esanj.ir/16-personality-factor-test"},
    {"id": 31, "title": "تست سبک های مقابله با استرس (CSI)", "url": "https://esanj.ir/stress-coping-styles"},
    {"id": 32, "title": "تست انگیزش تحصیلی هارتر (HEMS)", "url": "https://esanj.ir/educational-motivation-scale"},
    {"id": 33, "title": "تست قدرت تخیل (PIQ)", "url": "https://esanj.ir/power-of-imagination-test"},
    {"id": 34, "title": "تست اضطراب کتل (CAQ)", "url": "https://esanj.ir/online-anxiety-test"},
    {"id": 35, "title": "تست تجسم فضایی مینه سوتا (SVT)", "url": "https://esanj.ir/spatial-visualization"},
    {"id": 36, "title": "تست اضطراب مرگ (FOD)", "url": "https://esanj.ir/fear-of-death"},
    {"id": 37, "title": "تست تعهد سازمانی آلن و مایر (OCQ)", "url": "https://esanj.ir/organizational-commitment-questionnaire"},
    {"id": 38, "title": "تست افسردگی کودکان و نوجوانان ماریاکواس (CDI)", "url": "https://esanj.ir/childrens-depression-inventory"},
    {"id": 39, "title": "تست عشق مثلثی استرنبرگ (STLS)", "url": "https://esanj.ir/sternberg-triangular-love-scale"},
    {"id": 40, "title": "تست وسواس فکری مادزلی (MOCI)", "url": "https://esanj.ir/Maudsley-Obsessive-Compulsive-Inventory"},
    {"id": 41, "title": "تست ترس های قبل از ازدواج (PFS)", "url": "https://esanj.ir/premarital-fears-scale"},
    {"id": 42, "title": "تست عادت مطالعه پالسانی و شارما (PSSHI)", "url": "https://esanj.ir/palsane-and-sharma-study-habit-inventory"},
    {"id": 43, "title": "تست شخصیت کارآفرین (EPT)", "url": "https://esanj.ir/entrepreneur-personality-test"},
    {"id": 44, "title": "تست هوش هیجانی (EQ) شات", "url": "https://esanj.ir/schutte-self-report-emotional-intelligence-test"},
    {"id": 45, "title": "تست هوش چندگانه گاردنر - مک کنزی (MII)", "url": "https://esanj.ir/multiple-intelligences-inventory"},
    {"id": 46, "title": "تست شخصیت شناسی MBTI", "url": "https://esanj.ir/myers-briggs-type-indicator-mbti"},
    {"id": 47, "title": "تست تصور از خدا (GII)", "url": "https://esanj.ir/the-god-image-inventory"},
    {"id": 48, "title": "تست سلامت روان (GHQ)", "url": "https://esanj.ir/general-health-questionnaire"},
    {"id": 49, "title": "تست جرأت ورزی جنسی هالبرت (HISA)", "url": "https://esanj.ir/hulbert-index-of-sexual-assertiveness"},
    {"id": 50, "title": "تست اهمال کاری تاکمن (TPS)", "url": "https://esanj.ir/tuckman-procrastination-scale"},
    {"id": 51, "title": "تست فرسودگی شغلی گلدارد (GBI) - ویژه روانشناسان", "url": "https://esanj.ir/geldard-burnout-inventory-test"},
    {"id": 52, "title": "تست اعتياد به اينترنت يانگ (IAT)", "url": "https://esanj.ir/internet-addiction-test"},
    {"id": 53, "title": "تست هوش IQ کتل کودکان - فرم B", "url": "https://esanj.ir/cattell-iq-test-ll-form-b-child"},
    {"id": 54, "title": "تست هوش IQ کتل کودکان - فرم A", "url": "https://esanj.ir/cattell-iq-test-ll-form-a-child"},
    {"id": 55, "title": "تست هوش IQ ریون کودکان (RCPM)", "url": "https://esanj.ir/ravens-colored-progressive-matrices-test"},
    {"id": 56, "title": "تست هوش IQ ریون", "url": "https://esanj.ir/ravens-progressive-matrices-test"},
    {"id": 57, "title": "تست هوش غیرکلامی بوناردل (BNIT)", "url": "https://esanj.ir/bonardels-nonverbal-intelligence-test"},
    {"id": 58, "title": "تست افسردگی بک (BDI-ll)", "url": "https://esanj.ir/online-depression-test"},
    {"id": 59, "title": "تست رضایت شغلی مینه سوتا (MSQ)", "url": "https://esanj.ir/minnesota-satisfaction-questionnaire"},
    {"id": 60, "title": "تست رغبت سنج تحصیلی و شغلی استرانگ", "url": "https://esanj.ir/strong-educational-occupational-interest-inventory"},
    {"id": 61, "title": "تست رضایت زناشویی انریچ (EMSS)", "url": "https://esanj.ir/enrich-marital-satisfaction-scale"},
    {"id": 62, "title": "تست هوش IQ کتل (فرم - A)", "url": "https://esanj.ir/cattell-intelligence-test-online"},
    {"id": 63, "title": "تست هوش تصویری IQ کتل - فرم B", "url": "https://esanj.ir/cattell-intelligence-test-online-b"},
    {"id": 64, "title": "تست شادکامی آکسفورد (OHI)", "url": "https://esanj.ir/oxford-happiness-test"},
    {"id": 65, "title": "تست هوش هیجانی (EQ) بار-آن", "url": "https://esanj.ir/bar-on-emotional-intelligence"},
]

TEST_CATALOG_BY_ID = {item["id"]: item for item in TEST_CATALOG}
