import { defineConfig } from "vitepress";

export default defineConfig({
  title: "Vania Developer Docs",
  description: "Technical documentation for the Vania platform.",
  lang: "en-US",
  cleanUrls: true,
  appearance: false,
  head: [
    ["link", { rel: "icon", href: "/logo.png" }],
    ["meta", { name: "theme-color", content: "#0f766e" }],
  ],
  themeConfig: {
    logo: "/logo.png",
    siteTitle: "Vania Docs",
    nav: [
      { text: "Guide", link: "/" },
      { text: "Architecture", link: "/architecture/system-overview" },
      { text: "API", link: "/api/overview" },
    ],
    sidebar: [
      {
        text: "Start Here",
        items: [
          { text: "Documentation Map", link: "/" },
          { text: "Local Development", link: "/getting-started/local-development" },
          { text: "Repository Tour", link: "/getting-started/repository-tour" },
        ],
      },
      {
        text: "Architecture",
        items: [
          { text: "System Overview", link: "/architecture/system-overview" },
          { text: "Application Boundaries", link: "/architecture/application-boundaries" },
          { text: "Request Routing", link: "/architecture/request-routing" },
          { text: "Runtime Flows", link: "/architecture/runtime-flows" },
          { text: "Data Model", link: "/architecture/data-model" },
          { text: "Context Propagation", link: "/architecture/context-propagation" },
          { text: "Extension Points", link: "/architecture/extension-points" },
          { text: "Access Architecture", link: "/architecture/access-architecture" },
          { text: "State and Persistence", link: "/architecture/state-and-persistence" },
        ],
      },
      {
        text: "Backend",
        items: [
          { text: "Django App", link: "/backend/django-app" },
          { text: "Configuration", link: "/backend/configuration" },
          { text: "Auth and Users", link: "/backend/auth-users" },
          { text: "Services and Access", link: "/backend/services-access" },
          { text: "Billing", link: "/backend/billing" },
          { text: "Agent Runtime", link: "/backend/agent-runtime" },
          { text: "Capabilities", link: "/backend/capabilities" },
          { text: "Canvas Backend", link: "/backend/canvas-backend" },
          { text: "Vania Core", link: "/backend/vania-core" },
          { text: "RAG and Attachments", link: "/backend/rag-attachments" },
          { text: "Background Jobs", link: "/backend/background-jobs" },
          { text: "Definitions Sync", link: "/backend/definitions-sync" },
          { text: "Backend Validation", link: "/backend/backend-validation" },
        ],
      },
      {
        text: "Frontend",
        items: [
          { text: "Next App", link: "/frontend/next-app" },
          { text: "Routing and Layouts", link: "/frontend/routing-layouts" },
          { text: "Auth and User State", link: "/frontend/auth-user-state" },
          { text: "API Client", link: "/frontend/api-client" },
          { text: "Chat Workspace", link: "/frontend/chat-workspace" },
          { text: "AG-UI Runtime", link: "/frontend/ag-ui-runtime" },
          { text: "Canvas UI", link: "/frontend/canvas-ui" },
          { text: "Dashboard", link: "/frontend/dashboard" },
          { text: "Public Pages", link: "/frontend/public-pages" },
          { text: "State Management", link: "/frontend/state-management" },
          { text: "Components and UI", link: "/frontend/components-and-ui" },
          { text: "Styling and Localization", link: "/frontend/styling-localization" },
          { text: "Frontend Validation", link: "/frontend/frontend-validation" },
        ],
      },
      {
        text: "Agents and Capabilities",
        items: [
          { text: "Agent Definitions", link: "/agents/agent-definitions" },
          { text: "Agent Lifecycle", link: "/agents/agent-lifecycle" },
          { text: "Discovery and Sync", link: "/agents/discovery-and-sync" },
          { text: "Capability System", link: "/agents/capability-system" },
          { text: "Runtime Hooks", link: "/agents/runtime-hooks" },
          { text: "Capability Domains", link: "/agents/capability-domains" },
          { text: "Tools and Forms", link: "/agents/tools-and-forms" },
          { text: "Canvas Integration", link: "/agents/canvas-integration" },
          { text: "Access and Demo Behavior", link: "/agents/access-and-demo-behavior" },
          { text: "Testing and Debugging", link: "/agents/testing-and-debugging" },
        ],
      },
      {
        text: "Canvas",
        items: [
          { text: "Canvas Contract", link: "/canvas/canvas-contract" },
          { text: "Canvas Lifecycle", link: "/canvas/canvas-lifecycle" },
          { text: "Backend Canvas", link: "/canvas/backend-canvas" },
          { text: "Canvas Models", link: "/canvas/canvas-models" },
          { text: "Hydration and Context", link: "/canvas/hydration-and-context" },
          { text: "Updates and Sync", link: "/canvas/updates-and-sync" },
          { text: "State Shapes", link: "/canvas/state-shapes" },
          { text: "Frontend Renderers", link: "/canvas/frontend-renderers" },
          { text: "Demo and Access", link: "/canvas/demo-and-access" },
          { text: "Migrations", link: "/canvas/migrations" },
          { text: "Canvas Validation", link: "/canvas/canvas-validation" },
        ],
      },
      {
        text: "Roles and Access",
        items: [
          { text: "Roles", link: "/roles-access/roles" },
          { text: "Role Model", link: "/roles-access/role-model" },
          { text: "Expert Verification", link: "/roles-access/expert-verification" },
          { text: "Eligibility", link: "/roles-access/eligibility" },
          { text: "Service Access", link: "/roles-access/service-access" },
          { text: "Profession Policy", link: "/roles-access/profession-policy" },
          { text: "Resource Access", link: "/roles-access/resource-access" },
          { text: "Billing Access", link: "/roles-access/billing-access" },
          { text: "Frontend Guards", link: "/roles-access/frontend-guards" },
          { text: "Access Validation", link: "/roles-access/access-validation" },
        ],
      },
      {
        text: "API",
        items: [
          { text: "API Overview", link: "/api/overview" },
          { text: "Authentication", link: "/api/authentication" },
          { text: "Context Headers", link: "/api/context-headers" },
          { text: "Auth APIs", link: "/api/auth" },
          { text: "Billing APIs", link: "/api/billing" },
          { text: "Agent APIs", link: "/api/agents" },
          { text: "Canvas APIs", link: "/api/canvas" },
          { text: "Service APIs", link: "/api/services" },
          { text: "Vania APIs", link: "/api/vania" },
          { text: "Esanj APIs", link: "/api/esanj" },
          { text: "Errors and Status", link: "/api/errors-and-status" },
          { text: "Frontend Consumers", link: "/api/frontend-consumers" },
          { text: "API Validation", link: "/api/api-validation" },
        ],
      },
      {
        text: "Operations",
        items: [
          { text: "Environment", link: "/operations/environment" },
          { text: "Infrastructure", link: "/operations/infrastructure" },
          { text: "Process Model", link: "/operations/process-model" },
          { text: "Deployment", link: "/operations/deployment" },
          { text: "Storage and Files", link: "/operations/storage-and-files" },
          { text: "Background Jobs", link: "/operations/background-jobs" },
          { text: "Observability", link: "/operations/observability" },
          { text: "Backup and Recovery", link: "/operations/backup-and-recovery" },
          { text: "Runbooks", link: "/operations/runbooks" },
          { text: "Operations Validation", link: "/operations/operations-validation" },
        ],
      },
      {
        text: "Quality",
        items: [
          { text: "Testing Strategy", link: "/quality/testing-strategy" },
          { text: "Manual QA", link: "/quality/manual-qa" },
          { text: "Troubleshooting", link: "/quality/troubleshooting" },
        ],
      },
      {
        text: "Contributing",
        items: [
          { text: "Coding Standards", link: "/contributing/coding-standards" },
          { text: "Documentation Standards", link: "/contributing/documentation-standards" },
        ],
      },
    ],
    search: {
      provider: "local",
    },
    socialLinks: [],
    footer: {
      message: "Vania V2 technical documentation.",
      copyright: "Self-hosted with VitePress.",
    },
  },
});
