from .constants import OPTS_EDUCATION, OPTS_JOB_STATUS, OPTS_MARITAL_STATUS, OPTS_MILITARY, OPTS_SCORING_0_4


FORM_MARRIAGE = {
    "key": "MARRIAGE_V1",
    "title": "فرم شماره ۳: مشاوره ازدواج",
    "description": "ارزیابی پیش از ازدواج، مقایسه زوج و محاسبه درصد تشابه بر اساس ملاک‌های فرم کاغذی.",
    "handler": "MarriageAssessmentHandler",
    "schema": [
        {
            "type": "section",
            "name": "marriage_couple_profile",
            "title": "اطلاعات زوج",
            "description": "اطلاعات عمومی مراجع در پروفایل پایه ثبت می‌شود؛ این بخش برای جزئیات دو طرف رابطه و موارد اختصاصی فرم ازدواج است.",
            "fields": [
                {"name": "man_full_name", "label": "نام و نام خانوادگی آقا", "type": "text", "width": "half"},
                {"name": "woman_full_name", "label": "نام و نام خانوادگی خانم", "type": "text", "width": "half"},
                {"name": "man_national_id", "label": "شماره ملی آقا", "type": "text", "width": "half"},
                {"name": "woman_national_id", "label": "شماره ملی خانم", "type": "text", "width": "half"},
                {"name": "man_birth_date", "label": "تاریخ تولد آقا", "type": "date", "width": "half"},
                {"name": "woman_birth_date", "label": "تاریخ تولد خانم", "type": "date", "width": "half"},
                {"name": "man_education_level", "label": "وضعیت تحصیلی آقا", "type": "select", "options": OPTS_EDUCATION, "width": "half"},
                {"name": "woman_education_level", "label": "وضعیت تحصیلی خانم", "type": "select", "options": OPTS_EDUCATION, "width": "half"},
                {"name": "man_job_status", "label": "وضعیت اشتغال آقا", "type": "select", "options": OPTS_JOB_STATUS, "width": "half"},
                {"name": "woman_job_status", "label": "وضعیت اشتغال خانم", "type": "select", "options": OPTS_JOB_STATUS, "width": "half"},
                {"name": "man_job_title", "label": "عنوان شغل آقا", "type": "text", "width": "half"},
                {"name": "woman_job_title", "label": "عنوان شغل خانم", "type": "text", "width": "half"},
                {"name": "man_income_approx", "label": "درآمد ماهیانه آقا", "type": "text", "width": "half"},
                {"name": "woman_income_approx", "label": "درآمد ماهیانه خانم", "type": "text", "width": "half"},
                {"name": "man_mobile_phone", "label": "تلفن آقا", "type": "text", "width": "half"},
                {"name": "woman_mobile_phone", "label": "تلفن خانم", "type": "text", "width": "half"},
                {"name": "shared_home_address", "label": "نشانی محل سکونت", "type": "textarea", "width": "full"},
                {"name": "shared_work_address", "label": "نشانی محل کار", "type": "textarea", "width": "full"},
                {"name": "man_military_status", "label": "وضعیت نظام وظیفه آقا", "type": "select", "options": OPTS_MILITARY, "width": "half"},
                {"name": "man_military_notes", "label": "توضیحات نظام وظیفه / علت معافیت", "type": "text", "width": "half"},
            ],
        },
        {
            "type": "section",
            "name": "marriage_relationship_context",
            "title": "زمینه آشنایی و وضعیت فعلی",
            "description": "نحوه شکل‌گیری رابطه، وضعیت فعلی و بستر مشترک دو طرف را ثبت کنید.",
            "fields": [
                {"name": "acquaintance_mode", "label": "۹. نحوه آشنایی", "type": "textarea", "width": "full"},
                {"name": "acquaintance_duration", "label": "۱۰. مدت آشنایی", "type": "text", "width": "half"},
                {"name": "current_relationship_status", "label": "۱۱. وضعیت فعلی", "type": "select", "options": OPTS_MARITAL_STATUS, "width": "half"},
                {"name": "previous_marriage_history", "label": "۱۲. سابقه ازدواج قبلی", "type": "textarea", "width": "full"},
                {"name": "future_housing_status", "label": "۱۳. وضعیت مسکن پس از ازدواج", "type": "textarea", "width": "full"},
                {"name": "kinship_relation", "label": "۲۸. آیا نسبت فامیلی دارند؟", "type": "text", "width": "half"},
                {"name": "current_request", "label": "تقاضای فعلی / موضوع اصلی مراجعه", "type": "textarea", "width": "full"},
                {"name": "knowledge_of_each_other", "label": "۲۶. میزان شناخت از یکدیگر", "type": "textarea", "width": "full"},
            ],
        },
        {
            "type": "section",
            "name": "marriage_family_background",
            "title": "وضعیت خانواده و همسویی دیدگاه‌ها",
            "description": "طبقات خانواده، نظر خانواده‌ها، دیدگاه‌ها و سوابق مهم را مستند کنید.",
            "fields": [
                {"name": "social_class_review", "label": "۱۴. بررسی وضعیت طبقه اجتماعی خانواده", "type": "textarea", "width": "full"},
                {"name": "cultural_class_review", "label": "۱۵. بررسی وضعیت طبقه فرهنگی خانواده", "type": "textarea", "width": "full"},
                {"name": "economic_class_review", "label": "۱۶. بررسی وضعیت طبقه اقتصادی خانواده", "type": "textarea", "width": "full"},
                {"name": "family_opinion_about_marriage", "label": "۱۷. نظر خانواده طرفین درباره ازدواج", "type": "textarea", "width": "full"},
                {"name": "education_view_alignment", "label": "۱۸. دیدگاه طرفین درباره ادامه تحصیل", "type": "textarea", "width": "full"},
                {"name": "job_view_alignment", "label": "۱۹. دیدگاه طرفین درباره اشتغال", "type": "textarea", "width": "full"},
                {"name": "genetic_history_review", "label": "۲۰. سابقه اختلال‌های ژنتیک در خانواده", "type": "textarea", "width": "full"},
                {"name": "physical_health_history", "label": "۲۱. سابقه مشکلات جسمانی", "type": "textarea", "width": "full"},
                {"name": "mental_health_history", "label": "۲۲. سابقه مشکلات روانی", "type": "textarea", "width": "full"},
                {"name": "family_divorce_history", "label": "۲۳. سابقه طلاق در خانواده", "type": "textarea", "width": "full"},
                {"name": "family_addiction_history", "label": "۲۴. سابقه اعتیاد در خانواده", "type": "textarea", "width": "full"},
                {"name": "criminal_history_review", "label": "۲۵. سابقه کیفری در فرد و خانواده", "type": "textarea", "width": "full"},
                {"name": "religious_belief_review", "label": "۲۹. بررسی وضعیت اعتقادی و مذهبی", "type": "textarea", "width": "full"},
                {"name": "selection_criteria", "label": "۳۰. ملاک‌های انتخاب", "type": "textarea", "width": "full"},
                {"name": "expectations_text", "label": "۳۱. انتظارات", "type": "textarea", "width": "full"},
            ],
        },
        {
            "type": "section",
            "name": "marriage_tests_and_summary",
            "title": "آزمون‌ها و جمع‌بندی",
            "description": "نتایج آزمون‌ها، ملاحظات و جمع‌بندی تخصصی مشاور را ثبت کنید.",
            "fields": [
                {"name": "test_results_summary", "label": "۲۷. نتایج حاصله از اجرای آزمون‌ها", "type": "textarea", "width": "full"},
                {"name": "special_conditions", "label": "شرایط خاص و ملاحظات تکمیلی", "type": "textarea", "width": "full"},
                {"name": "final_summary", "label": "جمع‌بندی نهایی", "type": "textarea", "width": "full"},
                {"name": "advisor_suggestion", "label": "۵. اظهار نظر مشاور با ذکر راهبردها و توصیه‌ها", "type": "textarea", "width": "full"},
            ],
        },
        {
            "type": "section",
            "name": "marriage_scoring",
            "title": "نمره‌گذاری ملاک‌ها",
            "description": "برای هر ملاک امتیاز ۰ تا ۴ را بر اساس فرم ازدواج ثبت کنید. درصد تشابه بر مبنای فرمول فرم محاسبه می‌شود.",
            "fields": [
                {"name": "score_age", "label": "۱. تناسب سن", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_education", "label": "۲. تناسب تحصیلات", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_job", "label": "۳. تناسب شغل", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_income", "label": "۴. تناسب درآمد ماهیانه", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_military", "label": "۸. وضعیت نظام وظیفه", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_acquaintance_mode", "label": "۹. نحوه آشنایی", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_acquaintance_duration", "label": "۱۰. مدت آشنایی", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_marriage_history", "label": "۱۲. سابقه ازدواج قبلی", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_housing", "label": "۱۳. وضعیت مسکن پس از ازدواج", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_social_class", "label": "۱۴. وضعیت طبقه اجتماعی خانواده", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_cultural_class", "label": "۱۵. وضعیت طبقه فرهنگی خانواده", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_economic_class", "label": "۱۶. وضعیت طبقه اقتصادی خانواده", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_family_opinion", "label": "۱۷. نظر خانواده طرفین درباره ازدواج", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_education_view", "label": "۱۸. دیدگاه طرفین درباره ادامه تحصیل", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_job_view", "label": "۱۹. دیدگاه طرفین درباره اشتغال", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_genetic_history", "label": "۲۰. سابقه اختلال‌های ژنتیک در خانواده", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_health_history", "label": "۲۱. سابقه مشکلات جسمانی", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_mental_history", "label": "۲۲. سابقه مشکلات روانی", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_divorce_history", "label": "۲۳. سابقه طلاق در خانواده", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_addiction_history", "label": "۲۴. سابقه اعتیاد در خانواده", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_criminal_history", "label": "۲۵. سابقه کیفری در فرد و خانواده", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_knowledge", "label": "۲۶. میزان شناخت از یکدیگر", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_test_results", "label": "۲۷. نتایج آزمون‌ها", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_belief_alignment", "label": "۲۹. وضعیت اعتقادی و مذهبی", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_criteria_alignment", "label": "۳۰. ملاک‌های انتخاب", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "score_expectations", "label": "۳۱. انتظارات", "type": "select", "options": OPTS_SCORING_0_4, "width": "half"},
                {"name": "scoring_notes", "label": "ملاحظات نمره‌گذاری", "type": "textarea", "width": "full"},
            ],
        },
    ],
}
