from .constants import (
    OPTS_EDUCATION,
    OPTS_JOB_STATUS,
    OPTS_MARITAL_STATUS,
    OPTS_MILITARY,
    OPTS_REFERRAL,
)


FORM_BASE_PROFILE = {
    "key": "BASE_PROFILE_V1",
    "title": "پروفایل پایه مراجع",
    "description": "اطلاعات هویتی، ارتباطی، شغلی، خانوادگی و شبکه‌های اجتماعی مراجع که بین خود او و متخصصان مشترک است.",
    "handler": "GenericFormHandler",
    "schema": [
        {
            "type": "section",
            "name": "profile_identity",
            "title": "هویت و پرونده",
            "description": "مشخصات اصلی مراجع و اطلاعات پایه پرونده را ثبت کنید.",
            "fields": [
                {"name": "file_number", "label": "شماره پرونده مراجع", "type": "text", "width": "half"},
                {"name": "file_date", "label": "تاریخ تشکیل پرونده", "type": "date", "width": "half"},
                {"name": "full_name", "label": "نام و نام خانوادگی", "type": "text", "width": "half", "required": True},
                {"name": "national_id", "label": "شماره ملی", "type": "text", "width": "half"},
                {"name": "gender", "label": "جنسیت", "type": "select", "options": ["مؤنث", "مذکر"], "width": "half"},
                {"name": "birth_date", "label": "تاریخ تولد", "type": "date", "width": "half"},
            ],
        },
        {
            "type": "section",
            "name": "contact_details",
            "title": "راه‌های ارتباطی",
            "description": "اطلاعات تماس و نشانی‌های اصلی مراجع را اینجا نگه دارید.",
            "fields": [
                {"name": "mobile_phone", "label": "شماره موبایل", "type": "text", "width": "half"},
                {"name": "home_phone", "label": "تلفن ثابت", "type": "text", "width": "half"},
                {"name": "email", "label": "ایمیل", "type": "email", "width": "half"},
                {"name": "preferred_contact_method", "label": "راه ارتباطی ترجیحی", "type": "text", "width": "half"},
                {"name": "address_home", "label": "نشانی محل سکونت", "type": "textarea", "width": "full"},
                {"name": "address_work", "label": "نشانی محل کار", "type": "textarea", "width": "full"},
            ],
        },
        {
            "type": "section",
            "name": "life_status",
            "title": "وضعیت فردی، تحصیلی و شغلی",
            "description": "وضعیت فعلی زندگی، تحصیل و شغل مراجع را در بخش‌های جدا ثبت کنید.",
            "fields": [
                {"name": "marital_status", "label": "وضعیت تأهل", "type": "select", "options": OPTS_MARITAL_STATUS, "width": "half"},
                {"name": "family_relation", "label": "نسبت فامیلی با همسر (در صورت وجود)", "type": "text", "width": "half"},
                {"name": "children_count", "label": "تعداد فرزندان", "type": "number", "width": "half"},
                {"name": "education_level", "label": "وضعیت تحصیلی", "type": "select", "options": OPTS_EDUCATION, "width": "half"},
                {"name": "education_major", "label": "عنوان رشته تحصیلی و مقطع", "type": "text", "width": "full"},
                {"name": "military_status", "label": "وضعیت نظام وظیفه", "type": "select", "options": OPTS_MILITARY, "width": "half"},
                {"name": "military_exempt_reason", "label": "علت معافیت", "type": "text", "width": "half"},
                {"name": "job_status", "label": "وضعیت شغلی", "type": "select", "options": OPTS_JOB_STATUS, "width": "half"},
                {"name": "job_type", "label": "نوع شغل", "type": "select", "options": ["آزاد", "دولتی"], "width": "half"},
                {"name": "job_title", "label": "عنوان شغل", "type": "text", "width": "half"},
                {"name": "income_approx", "label": "درآمد تقریبی", "type": "text", "width": "half"},
            ],
        },
        {
            "type": "section",
            "name": "social_links",
            "title": "شبکه‌های اجتماعی و حضور آنلاین",
            "description": "در صورت تمایل، لینک یا شناسه حساب‌های آنلاین مراجع را ثبت کنید.",
            "fields": [
                {"name": "social_instagram", "label": "اینستاگرام", "type": "text", "width": "half", "placeholder": "@username یا لینک"},
                {"name": "social_x", "label": "ایکس", "type": "text", "width": "half", "placeholder": "@username یا لینک"},
                {"name": "social_linkedin", "label": "لینکدین", "type": "text", "width": "half", "placeholder": "لینک پروفایل"},
                {"name": "social_telegram", "label": "تلگرام", "type": "text", "width": "half", "placeholder": "@username یا لینک"},
                {"name": "social_website", "label": "وب‌سایت شخصی", "type": "text", "width": "half", "placeholder": "https://example.com"},
                {"name": "social_other", "label": "سایر راه‌های آنلاین", "type": "text", "width": "half"},
            ],
        },
        {
            "type": "section",
            "name": "referral_and_family",
            "title": "ارجاع و تاریخچه خانوادگی",
            "description": "نحوه آشنایی با مجموعه و اطلاعات پایه خانواده را ساختارمند نگه دارید.",
            "fields": [
                {
                    "name": "referral_source",
                    "label": "منبع ارجاع",
                    "type": "checkbox_group",
                    "options": OPTS_REFERRAL,
                    "help_text": "در صورت نیاز می‌توانید چند مورد را هم‌زمان انتخاب کنید.",
                    "width": "full",
                },
                {
                    "name": "family_history",
                    "label": "جدول تاریخچه خانوادگی",
                    "type": "datagrid",
                    "width": "full",
                    "help_text": "برای هر عضو خانواده یک سطر جدا ثبت کنید.",
                    "columns": [
                        {"name": "name", "label": "نام و نام خانوادگی", "type": "text"},
                        {"name": "relation", "label": "نسبت", "type": "select", "options": ["پدر", "مادر", "خواهر", "برادر", "همسر", "فرزند", "سایر"]},
                        {"name": "age", "label": "سن", "type": "number"},
                        {"name": "education", "label": "تحصیلات", "type": "text"},
                        {"name": "job", "label": "شغل", "type": "text"},
                        {"name": "marital", "label": "تأهل", "type": "select", "options": ["مجرد", "متاهل", "مطلقه", "بیوه"]},
                        {"name": "note", "label": "توضیحات", "type": "text"},
                    ],
                },
            ],
        },
    ],
}
