# Generated by Django 4.2.7 on 2026-01-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_agentservice_interaction_forms_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontextentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usercontextentry',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='usercontextentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContextDefinition',
        ),
        migrations.DeleteModel(
            name='UserContextEntry',
        ),
    ]
