# Generated by Codex on 2026-02-24
from django.db import migrations


def forwards(apps, schema_editor):
    UserRole = apps.get_model("users", "UserRole")

    try:
        expert = UserRole.objects.get(slug="doctor")
        expert.slug = "expert"
        expert.name = "متخصص"
        expert.save(update_fields=["slug", "name"])
    except UserRole.DoesNotExist:
        UserRole.objects.update_or_create(
            slug="expert",
            defaults={"name": "متخصص"},
        )

    try:
        visitor = UserRole.objects.get(slug="patient")
        visitor.slug = "visitor"
        visitor.name = "مراجعه‌کننده"
        visitor.save(update_fields=["slug", "name"])
    except UserRole.DoesNotExist:
        UserRole.objects.update_or_create(
            slug="visitor",
            defaults={"name": "مراجعه‌کننده"},
        )


def backwards(apps, schema_editor):
    UserRole = apps.get_model("users", "UserRole")

    try:
        doctor = UserRole.objects.get(slug="expert")
        doctor.slug = "doctor"
        doctor.name = "پزشک"
        doctor.save(update_fields=["slug", "name"])
    except UserRole.DoesNotExist:
        pass

    try:
        patient = UserRole.objects.get(slug="visitor")
        patient.slug = "patient"
        patient.name = "بیمار"
        patient.save(update_fields=["slug", "name"])
    except UserRole.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_otprequest_customuser_is_verified_doctor_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
