# Generated by Django 4.2.7 on 2026-04-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_expertprofession_customuser_expert_verification_meta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="national_code",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]

